spring:
  application:
    name: lead-detector
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb

google:
  places:
    url: https://maps.googleapis.com/maps/api/place
    api-key: SUA_CHAVE_AQU